/*
 * Copyright contributors to Paladin, an LFDT project
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package org.lfdt.paladin.sdk.core.abi;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * A single input/output parameter (or event/error field) of an {@link AbiEntry}, mirroring {@code
 * abi.Parameter} from firefly-signer.
 *
 * <p>Immutable and self-serializing: {@code name} and {@code type} are always emitted, while {@code
 * internalType}, {@code components}, and {@code indexed} follow the Go {@code omitempty} convention
 * and are omitted when empty/false. Round-trips through any {@code ObjectMapper}.
 *
 * <p>Tuple (struct) parameters carry their nested fields in {@link #components()}.
 */
@JsonPropertyOrder({"name", "type", "internalType", "components", "indexed"})
public final class AbiParameter {

  private final String name;
  private final String type;
  private final String internalType;
  private final List<AbiParameter> components;
  private final boolean indexed;

  @JsonCreator
  AbiParameter(
      @JsonProperty("name") String name,
      @JsonProperty("type") String type,
      @JsonProperty("internalType") String internalType,
      @JsonProperty("components") List<AbiParameter> components,
      @JsonProperty("indexed") boolean indexed) {
    this.name = name == null ? "" : name;
    this.type = type == null ? "" : type;
    this.internalType = internalType;
    this.components = components == null ? List.of() : List.copyOf(components);
    this.indexed = indexed;
  }

  /**
   * The parameter name; does not affect the ABI signature. Empty string when unnamed.
   *
   * @return the parameter name, or an empty string when unnamed
   */
  @JsonProperty("name")
  public String name() {
    return name;
  }

  /**
   * The canonical ABI type of the parameter (e.g. {@code "uint256"}, {@code "address"}, {@code
   * "tuple"}).
   *
   * @return the canonical ABI type
   */
  @JsonProperty("type")
  public String type() {
    return type;
  }

  /**
   * Additional internal type information generated by the compiler, or {@code null} if absent.
   *
   * @return the internal type, or {@code null} if absent
   */
  @JsonProperty("internalType")
  @JsonInclude(JsonInclude.Include.NON_EMPTY)
  public String internalType() {
    return internalType;
  }

  /**
   * The ordered nested fields for tuple/array types; empty when this is an elementary type.
   *
   * @return the nested component parameters (never null, empty for elementary types)
   */
  @JsonProperty("components")
  @JsonInclude(JsonInclude.Include.NON_EMPTY)
  public List<AbiParameter> components() {
    return components;
  }

  /**
   * Events only: whether the parameter is indexed into a log topic rather than the data segment.
   *
   * @return {@code true} if the parameter is indexed
   */
  @JsonProperty("indexed")
  @JsonInclude(JsonInclude.Include.NON_DEFAULT)
  public boolean indexed() {
    return indexed;
  }

  /**
   * Creates an elementary parameter with the given name and canonical type.
   *
   * @param name the parameter name (may be empty when unnamed)
   * @param type the canonical ABI type
   * @return a new elementary {@code AbiParameter}
   */
  public static AbiParameter of(String name, String type) {
    return new AbiParameter(name, type, null, null, false);
  }

  /**
   * Starts a builder for a parameter with the given name and canonical type.
   *
   * @param name the parameter name (may be empty when unnamed)
   * @param type the canonical ABI type
   * @return a new builder
   */
  public static Builder builder(String name, String type) {
    return new Builder(name, type);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    return o instanceof AbiParameter other
        && indexed == other.indexed
        && name.equals(other.name)
        && type.equals(other.type)
        && Objects.equals(internalType, other.internalType)
        && components.equals(other.components);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, internalType, components, indexed);
  }

  @Override
  public String toString() {
    return "AbiParameter{name=" + name + ", type=" + type + (indexed ? ", indexed" : "") + "}";
  }

  /** Fluent builder for {@link AbiParameter}. */
  public static final class Builder {
    private final String name;
    private final String type;
    private String internalType;
    private final List<AbiParameter> components = new ArrayList<>();
    private boolean indexed;

    private Builder(String name, String type) {
      this.name = name;
      this.type = type;
    }

    /**
     * Sets the compiler-generated internal type.
     *
     * @param internalType the internal type information
     * @return this builder
     */
    public Builder internalType(String internalType) {
      this.internalType = internalType;
      return this;
    }

    /**
     * Adds a nested field for a tuple/array type.
     *
     * @param component the nested component parameter to add
     * @return this builder
     */
    public Builder component(AbiParameter component) {
      this.components.add(component);
      return this;
    }

    /**
     * Adds nested fields for a tuple/array type.
     *
     * @param components the nested component parameters to add
     * @return this builder
     */
    public Builder components(List<AbiParameter> components) {
      this.components.addAll(components);
      return this;
    }

    /**
     * Sets the {@code indexed} flag (events only).
     *
     * @param indexed whether the parameter is indexed into a log topic
     * @return this builder
     */
    public Builder indexed(boolean indexed) {
      this.indexed = indexed;
      return this;
    }

    /**
     * Builds the immutable {@link AbiParameter}.
     *
     * @return a new {@link AbiParameter} with the configured values
     */
    public AbiParameter build() {
      return new AbiParameter(name, type, internalType, components, indexed);
    }
  }
}
